<p style="font-family: Arial; font-size:3em;color:black;"> Lab 1 </p>

Students name in this Group:  
Nooh Faisal\
Wai Hong Fung\
Mae Lam\
Ho Kong Leung\
Mayuresh Nerurkar\
Ramana Surriyan Rajendran\
Hanlun Wang\
Wing Han Yiu

Group 9

In [2]:
# importing numpy
import numpy as np


In [3]:
# Create a numpy array with the elements "1, 2, 3, 5, 0", print the array and test if all of its elements are non-zero.
a = np.array([1, 2, 3, 5, 0])
print(a)
a_all_nonzero = np.all(a)
print(f"All of {a}'s elements are non-zero: {a_all_nonzero}")


[1 2 3 5 0]
All of [1 2 3 5 0]'s elements are non-zero: False


In [4]:
# Create a numpy array with the elements "3, -1, 3, 7, 2", print the array and test if any of its elements is non-zero.
b = np.array([3, -1, 3, 7, 2])
print(b)
b_any_nonzero = np.any(b)
print(f"Any of {b}'s elements is non-zero: {b_any_nonzero}")


[ 3 -1  3  7  2]
Any of [ 3 -1  3  7  2]'s elements is non-zero: True


In [5]:
# Create a numpy array with the elements "0, 0, 0, 0", print the array and test if any of its elements is non-zero.
c = np.array([0, 0, 0, 0])
print(c)
c_any_nonzero = np.any(c)
print(f"Any of {c}'s elements is non-zero: {c_any_nonzero}")

[0 0 0 0]
Any of [0 0 0 0]'s elements is non-zero: False


In [6]:
# Create a numpy array with the elements "56, -2, 7", print the array and the amount of memory required to store it.
d = np.array([56, -2, 7])
print(d)
d_memory_size = d.nbytes
print(f"The amount of memory required to store {d} is: {d_memory_size} bytes")

[56 -2  7]
The amount of memory required to store [56 -2  7] is: 24 bytes


In [7]:
# Create a numpy array with 10 zeros and print the array.
e = np.zeros(10)
print(e)

# Create a numpy array with 6 ones and print the array.
f = np.ones(6)
print(f)

# Create a numpy array with 12 '3's and print the array. [3 3 3 3 3 3 3 3 3 3 3 3]
g = np.ones(12)*3
print(g)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]
[3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]


In [8]:
# Create a numpy array of the integers from 8 to 20 and print the array. (make sure 20 itself is included) hint:  use "arange" method
h = np.arange(8, 21)
print(h)

# Create a numpy array of the even integers from 8 to 20 and print the array. (make sure 20 itself is included)   hint:  use "arange" method
i = np.arange(8, 21, 2)
print(i)


[ 8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 8 10 12 14 16 18 20]


In [9]:
# Create a numpy array consisting of 100 random elements from normal distribution with mean of 2 and std of 0.5. Print the mean, max, min and std of the array.
j = np.random.normal(2, 0.5, 100)
print(f"mean: {np.mean(j)}, max: {np.max(j)}, min: {np.min(j)}, std: {np.std(j)}")

# Create a numpy array consisting of 1000 random elements from normal distribution with mean of 2 and std of 0.5. Print the mean, max, min and std of the array.
k = np.random.normal(2, 0.5, 1000)
print(f"mean: {np.mean(k)}, max: {np.max(k)}, min: {np.min(k)}, std: {np.std(k)}")

# Create a numpy array consisting of 1000000 random elements from normal distribution with mean of 2 and std of 0.5. Print the mean, max, min and std of the array.
l = np.random.normal(2, 0.5, 1000000)
print(f"mean: {np.mean(l)}, max: {np.max(l)}, min: {np.min(l)}, std: {np.std(l)}")

# (Bonus question) Looking at the three above examples with 1000, 5000, and 10000 random elements, do you have any observations about mean and std values?
# The mean and std values are very similar and very close to the number we set. The mean is close to 2 and std is close to 0.5.



mean: 1.992067075171545, max: 3.309926131349738, min: 0.46750331127331246, std: 0.545651191008055
mean: 1.9872793557939046, max: 3.2838040682051113, min: 0.4219622881517784, std: 0.4960163921074563
mean: 1.9991399610647638, max: 4.542547501251583, min: -0.7152316925328646, std: 0.50031897127928
