<p style="font-family: Arial; font-size:3em;color:black;"> Lab Exercise 4 </p>

Students name in this Group:  
Nooh Faisal\
Wai Hong Fung\
Mae Lam\
Ho Kong Leung\
Mayuresh Nerurkar\
Ramana Surriyan Rajendran\
Hanlun Wang\
Wing Han Yiu

In [1]:
import numpy as np
from numpy.linalg import inv
from numpy.linalg import det

In [13]:
A = np.array([[5,2,3],[6,1,3],[2,4,1]])
print(A)
B = A[:2, :2]
print(B)
C = A[1:, 1:]
print(C)

[[5 2 3]
 [6 1 3]
 [2 4 1]]
[[5 2]
 [6 1]]
[[1 3]
 [4 1]]


In [14]:
D = np.array([[4,-7,4],[5,6,-1],[-4,2,5]])
print(D)

[[ 4 -7  4]
 [ 5  6 -1]
 [-4  2  5]]


In [15]:
AD = np.matmul(A,D)
print(AD)
DA = np.matmul(D,A)
print(DA)

[[ 18 -17  33]
 [ 17 -30  38]
 [ 24  12   9]]
[[-14  17  -5]
 [ 59  12  32]
 [  2  14  -1]]


AD and DA are not equal

In [16]:
B_det = np.linalg.det(B)
print(B_det)
B_inv = np.linalg.inv(B)
print(B_inv)

-6.999999999999998
[[-0.14285714  0.28571429]
 [ 0.85714286 -0.71428571]]


We have mannually calculated the det(B) is -7, so its almost the same.
inv B = 1/(-7)* [[1,-2],[-6,5]] = [[-1/7,2/7],[6/7,-5/7]], so its almost the same.

In [17]:
D_inv = np.linalg.inv(D)
DD_inv = np.matmul(D, D_inv)
print(DD_inv)
D_invD = np.matmul(D_inv, D)
print(D_invD)

[[ 1.00000000e+00  1.11022302e-16  0.00000000e+00]
 [ 1.38777878e-17  1.00000000e+00  0.00000000e+00]
 [ 5.55111512e-17 -8.32667268e-17  1.00000000e+00]]
[[ 1.00000000e+00  2.49800181e-16 -2.77555756e-17]
 [ 2.77555756e-17  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]


Although both of the matrices 3x3 identity matrices,
The values of both of them are different, hence the matrix multiplication is not commutative.